import Card, {
    VALUE_ACE,
    VALUE_EIGHT,
    VALUE_FIVE,
    VALUE_FOUR,
    VALUE_JACK,
    VALUE_KING,
    VALUE_NINE,
    VALUE_QUEEN,
    VALUE_SEVEN,
    VALUE_SIX,
    VALUE_TEN,
    VALUE_THREE,
    VALUE_TWO,
    SUIT_CLUBS,
    SUIT_DIAMOND,
    SUIT_HEART,
    SUIT_SPADE,
} from "./card";

export default class Deck {
    Cards: Card[] = [
        new Card(SUIT_CLUBS, VALUE_ACE),
        new Card(SUIT_CLUBS, VALUE_KING),
        new Card(SUIT_CLUBS, VALUE_QUEEN),
        new Card(SUIT_CLUBS, VALUE_JACK),
        new Card(SUIT_CLUBS, VALUE_TEN),
        new Card(SUIT_CLUBS, VALUE_NINE),
        new Card(SUIT_CLUBS, VALUE_EIGHT),
        new Card(SUIT_CLUBS, VALUE_SEVEN),
        new Card(SUIT_CLUBS, VALUE_SIX),
        new Card(SUIT_CLUBS, VALUE_FIVE),
        new Card(SUIT_CLUBS, VALUE_FOUR),
        new Card(SUIT_CLUBS, VALUE_THREE),
        new Card(SUIT_CLUBS, VALUE_TWO),
        new Card(SUIT_DIAMOND, VALUE_ACE),
        new Card(SUIT_DIAMOND, VALUE_KING),
        new Card(SUIT_DIAMOND, VALUE_QUEEN),
        new Card(SUIT_DIAMOND, VALUE_JACK),
        new Card(SUIT_DIAMOND, VALUE_TEN),
        new Card(SUIT_DIAMOND, VALUE_NINE),
        new Card(SUIT_DIAMOND, VALUE_EIGHT),
        new Card(SUIT_DIAMOND, VALUE_SEVEN),
        new Card(SUIT_DIAMOND, VALUE_SIX),
        new Card(SUIT_DIAMOND, VALUE_FIVE),
        new Card(SUIT_DIAMOND, VALUE_FOUR),
        new Card(SUIT_DIAMOND, VALUE_THREE),
        new Card(SUIT_DIAMOND, VALUE_TWO),
        new Card(SUIT_HEART, VALUE_ACE),
        new Card(SUIT_HEART, VALUE_KING),
        new Card(SUIT_HEART, VALUE_QUEEN),
        new Card(SUIT_HEART, VALUE_JACK),
        new Card(SUIT_HEART, VALUE_TEN),
        new Card(SUIT_HEART, VALUE_NINE),
        new Card(SUIT_HEART, VALUE_EIGHT),
        new Card(SUIT_HEART, VALUE_SEVEN),
        new Card(SUIT_HEART, VALUE_SIX),
        new Card(SUIT_HEART, VALUE_FIVE),
        new Card(SUIT_HEART, VALUE_FOUR),
        new Card(SUIT_HEART, VALUE_THREE),
        new Card(SUIT_HEART, VALUE_TWO),
        new Card(SUIT_SPADE, VALUE_ACE),
        new Card(SUIT_SPADE, VALUE_KING),
        new Card(SUIT_SPADE, VALUE_QUEEN),
        new Card(SUIT_SPADE, VALUE_JACK),
        new Card(SUIT_SPADE, VALUE_TEN),
        new Card(SUIT_SPADE, VALUE_NINE),
        new Card(SUIT_SPADE, VALUE_EIGHT),
        new Card(SUIT_SPADE, VALUE_SEVEN),
        new Card(SUIT_SPADE, VALUE_SIX),
        new Card(SUIT_SPADE, VALUE_FIVE),
        new Card(SUIT_SPADE, VALUE_FOUR),
        new Card(SUIT_SPADE, VALUE_THREE),
        new Card(SUIT_SPADE, VALUE_TWO),
    ]
}