import Card, {
  Kind,
  Suit
} from './card'

export default class Deck {
  Cards: Card[] = [
    new Card(Suit.Clubs, Kind.Ace),
    new Card(Suit.Clubs, Kind.King),
    new Card(Suit.Clubs, Kind.Queen),
    new Card(Suit.Clubs, Kind.Jack),
    new Card(Suit.Clubs, Kind.Ten),
    new Card(Suit.Clubs, Kind.Nine),
    new Card(Suit.Clubs, Kind.Eight),
    new Card(Suit.Clubs, Kind.Seven),
    new Card(Suit.Clubs, Kind.Six),
    new Card(Suit.Clubs, Kind.Five),
    new Card(Suit.Clubs, Kind.Four),
    new Card(Suit.Clubs, Kind.Three),
    new Card(Suit.Clubs, Kind.Two),
    new Card(Suit.Diamond, Kind.Ace),
    new Card(Suit.Diamond, Kind.King),
    new Card(Suit.Diamond, Kind.Queen),
    new Card(Suit.Diamond, Kind.Jack),
    new Card(Suit.Diamond, Kind.Ten),
    new Card(Suit.Diamond, Kind.Nine),
    new Card(Suit.Diamond, Kind.Eight),
    new Card(Suit.Diamond, Kind.Seven),
    new Card(Suit.Diamond, Kind.Six),
    new Card(Suit.Diamond, Kind.Five),
    new Card(Suit.Diamond, Kind.Four),
    new Card(Suit.Diamond, Kind.Three),
    new Card(Suit.Diamond, Kind.Two),
    new Card(Suit.Heart, Kind.Ace),
    new Card(Suit.Heart, Kind.King),
    new Card(Suit.Heart, Kind.Queen),
    new Card(Suit.Heart, Kind.Jack),
    new Card(Suit.Heart, Kind.Ten),
    new Card(Suit.Heart, Kind.Nine),
    new Card(Suit.Heart, Kind.Eight),
    new Card(Suit.Heart, Kind.Seven),
    new Card(Suit.Heart, Kind.Six),
    new Card(Suit.Heart, Kind.Five),
    new Card(Suit.Heart, Kind.Four),
    new Card(Suit.Heart, Kind.Three),
    new Card(Suit.Heart, Kind.Two),
    new Card(Suit.Spade, Kind.Ace),
    new Card(Suit.Spade, Kind.King),
    new Card(Suit.Spade, Kind.Queen),
    new Card(Suit.Spade, Kind.Jack),
    new Card(Suit.Spade, Kind.Ten),
    new Card(Suit.Spade, Kind.Nine),
    new Card(Suit.Spade, Kind.Eight),
    new Card(Suit.Spade, Kind.Seven),
    new Card(Suit.Spade, Kind.Six),
    new Card(Suit.Spade, Kind.Five),
    new Card(Suit.Spade, Kind.Four),
    new Card(Suit.Spade, Kind.Three),
    new Card(Suit.Spade, Kind.Two)
  ]
}
