import { v4 as uuidv4 } from 'uuid'
import Card, {
  SUIT_CLUBS,
  SUIT_DIAMOND,
  SUIT_HEART,
  SUIT_SPADE,
  KIND_TWO,
  KIND_THREE,
  KIND_FOUR,
  KIND_FIVE,
  KIND_SIX,
  KIND_SEVEN,
  KIND_EIGHT,
  KIND_NINE,
  KIND_TEN,
  KIND_JACK,
  KIND_QUEEN,
  KIND_KING,
  KIND_ACE,
} from '../card/card'

export default class Table {
  Id!: string
  Deck: Card[] = []

  constructor() {
    this.Id = uuidv4()

    this.ShuffleDeck()
  }

  CardsRemaining(): number {
    return this.Deck.length
  }

  DrawCard(): Card | undefined {
    return this.Deck.pop()
  }

  ShuffleDeck() {
    // NOTE: initializing deck with 6 decks
    this.Deck = [
      new Card(SUIT_CLUBS, KIND_ACE),
      new Card(SUIT_CLUBS, KIND_KING),
      new Card(SUIT_CLUBS, KIND_QUEEN),
      new Card(SUIT_CLUBS, KIND_JACK),
      new Card(SUIT_CLUBS, KIND_TEN),
      new Card(SUIT_CLUBS, KIND_NINE),
      new Card(SUIT_CLUBS, KIND_EIGHT),
      new Card(SUIT_CLUBS, KIND_SEVEN),
      new Card(SUIT_CLUBS, KIND_SIX),
      new Card(SUIT_CLUBS, KIND_FIVE),
      new Card(SUIT_CLUBS, KIND_FOUR),
      new Card(SUIT_CLUBS, KIND_THREE),
      new Card(SUIT_CLUBS, KIND_TWO),
      new Card(SUIT_DIAMOND, KIND_ACE),
      new Card(SUIT_DIAMOND, KIND_KING),
      new Card(SUIT_DIAMOND, KIND_QUEEN),
      new Card(SUIT_DIAMOND, KIND_JACK),
      new Card(SUIT_DIAMOND, KIND_TEN),
      new Card(SUIT_DIAMOND, KIND_NINE),
      new Card(SUIT_DIAMOND, KIND_EIGHT),
      new Card(SUIT_DIAMOND, KIND_SEVEN),
      new Card(SUIT_DIAMOND, KIND_SIX),
      new Card(SUIT_DIAMOND, KIND_FIVE),
      new Card(SUIT_DIAMOND, KIND_FOUR),
      new Card(SUIT_DIAMOND, KIND_THREE),
      new Card(SUIT_DIAMOND, KIND_TWO),
      new Card(SUIT_HEART, KIND_ACE),
      new Card(SUIT_HEART, KIND_KING),
      new Card(SUIT_HEART, KIND_QUEEN),
      new Card(SUIT_HEART, KIND_JACK),
      new Card(SUIT_HEART, KIND_TEN),
      new Card(SUIT_HEART, KIND_NINE),
      new Card(SUIT_HEART, KIND_EIGHT),
      new Card(SUIT_HEART, KIND_SEVEN),
      new Card(SUIT_HEART, KIND_SIX),
      new Card(SUIT_HEART, KIND_FIVE),
      new Card(SUIT_HEART, KIND_FOUR),
      new Card(SUIT_HEART, KIND_THREE),
      new Card(SUIT_HEART, KIND_TWO),
      new Card(SUIT_SPADE, KIND_ACE),
      new Card(SUIT_SPADE, KIND_KING),
      new Card(SUIT_SPADE, KIND_QUEEN),
      new Card(SUIT_SPADE, KIND_JACK),
      new Card(SUIT_SPADE, KIND_TEN),
      new Card(SUIT_SPADE, KIND_NINE),
      new Card(SUIT_SPADE, KIND_EIGHT),
      new Card(SUIT_SPADE, KIND_SEVEN),
      new Card(SUIT_SPADE, KIND_SIX),
      new Card(SUIT_SPADE, KIND_FIVE),
      new Card(SUIT_SPADE, KIND_FOUR),
      new Card(SUIT_SPADE, KIND_THREE),
      new Card(SUIT_SPADE, KIND_TWO),
      new Card(SUIT_CLUBS, KIND_ACE),
      new Card(SUIT_CLUBS, KIND_KING),
      new Card(SUIT_CLUBS, KIND_QUEEN),
      new Card(SUIT_CLUBS, KIND_JACK),
      new Card(SUIT_CLUBS, KIND_TEN),
      new Card(SUIT_CLUBS, KIND_NINE),
      new Card(SUIT_CLUBS, KIND_EIGHT),
      new Card(SUIT_CLUBS, KIND_SEVEN),
      new Card(SUIT_CLUBS, KIND_SIX),
      new Card(SUIT_CLUBS, KIND_FIVE),
      new Card(SUIT_CLUBS, KIND_FOUR),
      new Card(SUIT_CLUBS, KIND_THREE),
      new Card(SUIT_CLUBS, KIND_TWO),
      new Card(SUIT_DIAMOND, KIND_ACE),
      new Card(SUIT_DIAMOND, KIND_KING),
      new Card(SUIT_DIAMOND, KIND_QUEEN),
      new Card(SUIT_DIAMOND, KIND_JACK),
      new Card(SUIT_DIAMOND, KIND_TEN),
      new Card(SUIT_DIAMOND, KIND_NINE),
      new Card(SUIT_DIAMOND, KIND_EIGHT),
      new Card(SUIT_DIAMOND, KIND_SEVEN),
      new Card(SUIT_DIAMOND, KIND_SIX),
      new Card(SUIT_DIAMOND, KIND_FIVE),
      new Card(SUIT_DIAMOND, KIND_FOUR),
      new Card(SUIT_DIAMOND, KIND_THREE),
      new Card(SUIT_DIAMOND, KIND_TWO),
      new Card(SUIT_HEART, KIND_ACE),
      new Card(SUIT_HEART, KIND_KING),
      new Card(SUIT_HEART, KIND_QUEEN),
      new Card(SUIT_HEART, KIND_JACK),
      new Card(SUIT_HEART, KIND_TEN),
      new Card(SUIT_HEART, KIND_NINE),
      new Card(SUIT_HEART, KIND_EIGHT),
      new Card(SUIT_HEART, KIND_SEVEN),
      new Card(SUIT_HEART, KIND_SIX),
      new Card(SUIT_HEART, KIND_FIVE),
      new Card(SUIT_HEART, KIND_FOUR),
      new Card(SUIT_HEART, KIND_THREE),
      new Card(SUIT_HEART, KIND_TWO),
      new Card(SUIT_SPADE, KIND_ACE),
      new Card(SUIT_SPADE, KIND_KING),
      new Card(SUIT_SPADE, KIND_QUEEN),
      new Card(SUIT_SPADE, KIND_JACK),
      new Card(SUIT_SPADE, KIND_TEN),
      new Card(SUIT_SPADE, KIND_NINE),
      new Card(SUIT_SPADE, KIND_EIGHT),
      new Card(SUIT_SPADE, KIND_SEVEN),
      new Card(SUIT_SPADE, KIND_SIX),
      new Card(SUIT_SPADE, KIND_FIVE),
      new Card(SUIT_SPADE, KIND_FOUR),
      new Card(SUIT_SPADE, KIND_THREE),
      new Card(SUIT_SPADE, KIND_TWO),
      new Card(SUIT_CLUBS, KIND_ACE),
      new Card(SUIT_CLUBS, KIND_KING),
      new Card(SUIT_CLUBS, KIND_QUEEN),
      new Card(SUIT_CLUBS, KIND_JACK),
      new Card(SUIT_CLUBS, KIND_TEN),
      new Card(SUIT_CLUBS, KIND_NINE),
      new Card(SUIT_CLUBS, KIND_EIGHT),
      new Card(SUIT_CLUBS, KIND_SEVEN),
      new Card(SUIT_CLUBS, KIND_SIX),
      new Card(SUIT_CLUBS, KIND_FIVE),
      new Card(SUIT_CLUBS, KIND_FOUR),
      new Card(SUIT_CLUBS, KIND_THREE),
      new Card(SUIT_CLUBS, KIND_TWO),
      new Card(SUIT_DIAMOND, KIND_ACE),
      new Card(SUIT_DIAMOND, KIND_KING),
      new Card(SUIT_DIAMOND, KIND_QUEEN),
      new Card(SUIT_DIAMOND, KIND_JACK),
      new Card(SUIT_DIAMOND, KIND_TEN),
      new Card(SUIT_DIAMOND, KIND_NINE),
      new Card(SUIT_DIAMOND, KIND_EIGHT),
      new Card(SUIT_DIAMOND, KIND_SEVEN),
      new Card(SUIT_DIAMOND, KIND_SIX),
      new Card(SUIT_DIAMOND, KIND_FIVE),
      new Card(SUIT_DIAMOND, KIND_FOUR),
      new Card(SUIT_DIAMOND, KIND_THREE),
      new Card(SUIT_DIAMOND, KIND_TWO),
      new Card(SUIT_HEART, KIND_ACE),
      new Card(SUIT_HEART, KIND_KING),
      new Card(SUIT_HEART, KIND_QUEEN),
      new Card(SUIT_HEART, KIND_JACK),
      new Card(SUIT_HEART, KIND_TEN),
      new Card(SUIT_HEART, KIND_NINE),
      new Card(SUIT_HEART, KIND_EIGHT),
      new Card(SUIT_HEART, KIND_SEVEN),
      new Card(SUIT_HEART, KIND_SIX),
      new Card(SUIT_HEART, KIND_FIVE),
      new Card(SUIT_HEART, KIND_FOUR),
      new Card(SUIT_HEART, KIND_THREE),
      new Card(SUIT_HEART, KIND_TWO),
      new Card(SUIT_SPADE, KIND_ACE),
      new Card(SUIT_SPADE, KIND_KING),
      new Card(SUIT_SPADE, KIND_QUEEN),
      new Card(SUIT_SPADE, KIND_JACK),
      new Card(SUIT_SPADE, KIND_TEN),
      new Card(SUIT_SPADE, KIND_NINE),
      new Card(SUIT_SPADE, KIND_EIGHT),
      new Card(SUIT_SPADE, KIND_SEVEN),
      new Card(SUIT_SPADE, KIND_SIX),
      new Card(SUIT_SPADE, KIND_FIVE),
      new Card(SUIT_SPADE, KIND_FOUR),
      new Card(SUIT_SPADE, KIND_THREE),
      new Card(SUIT_SPADE, KIND_TWO),
      new Card(SUIT_CLUBS, KIND_ACE),
      new Card(SUIT_CLUBS, KIND_KING),
      new Card(SUIT_CLUBS, KIND_QUEEN),
      new Card(SUIT_CLUBS, KIND_JACK),
      new Card(SUIT_CLUBS, KIND_TEN),
      new Card(SUIT_CLUBS, KIND_NINE),
      new Card(SUIT_CLUBS, KIND_EIGHT),
      new Card(SUIT_CLUBS, KIND_SEVEN),
      new Card(SUIT_CLUBS, KIND_SIX),
      new Card(SUIT_CLUBS, KIND_FIVE),
      new Card(SUIT_CLUBS, KIND_FOUR),
      new Card(SUIT_CLUBS, KIND_THREE),
      new Card(SUIT_CLUBS, KIND_TWO),
      new Card(SUIT_DIAMOND, KIND_ACE),
      new Card(SUIT_DIAMOND, KIND_KING),
      new Card(SUIT_DIAMOND, KIND_QUEEN),
      new Card(SUIT_DIAMOND, KIND_JACK),
      new Card(SUIT_DIAMOND, KIND_TEN),
      new Card(SUIT_DIAMOND, KIND_NINE),
      new Card(SUIT_DIAMOND, KIND_EIGHT),
      new Card(SUIT_DIAMOND, KIND_SEVEN),
      new Card(SUIT_DIAMOND, KIND_SIX),
      new Card(SUIT_DIAMOND, KIND_FIVE),
      new Card(SUIT_DIAMOND, KIND_FOUR),
      new Card(SUIT_DIAMOND, KIND_THREE),
      new Card(SUIT_DIAMOND, KIND_TWO),
      new Card(SUIT_HEART, KIND_ACE),
      new Card(SUIT_HEART, KIND_KING),
      new Card(SUIT_HEART, KIND_QUEEN),
      new Card(SUIT_HEART, KIND_JACK),
      new Card(SUIT_HEART, KIND_TEN),
      new Card(SUIT_HEART, KIND_NINE),
      new Card(SUIT_HEART, KIND_EIGHT),
      new Card(SUIT_HEART, KIND_SEVEN),
      new Card(SUIT_HEART, KIND_SIX),
      new Card(SUIT_HEART, KIND_FIVE),
      new Card(SUIT_HEART, KIND_FOUR),
      new Card(SUIT_HEART, KIND_THREE),
      new Card(SUIT_HEART, KIND_TWO),
      new Card(SUIT_SPADE, KIND_ACE),
      new Card(SUIT_SPADE, KIND_KING),
      new Card(SUIT_SPADE, KIND_QUEEN),
      new Card(SUIT_SPADE, KIND_JACK),
      new Card(SUIT_SPADE, KIND_TEN),
      new Card(SUIT_SPADE, KIND_NINE),
      new Card(SUIT_SPADE, KIND_EIGHT),
      new Card(SUIT_SPADE, KIND_SEVEN),
      new Card(SUIT_SPADE, KIND_SIX),
      new Card(SUIT_SPADE, KIND_FIVE),
      new Card(SUIT_SPADE, KIND_FOUR),
      new Card(SUIT_SPADE, KIND_THREE),
      new Card(SUIT_SPADE, KIND_TWO),
      new Card(SUIT_CLUBS, KIND_ACE),
      new Card(SUIT_CLUBS, KIND_KING),
      new Card(SUIT_CLUBS, KIND_QUEEN),
      new Card(SUIT_CLUBS, KIND_JACK),
      new Card(SUIT_CLUBS, KIND_TEN),
      new Card(SUIT_CLUBS, KIND_NINE),
      new Card(SUIT_CLUBS, KIND_EIGHT),
      new Card(SUIT_CLUBS, KIND_SEVEN),
      new Card(SUIT_CLUBS, KIND_SIX),
      new Card(SUIT_CLUBS, KIND_FIVE),
      new Card(SUIT_CLUBS, KIND_FOUR),
      new Card(SUIT_CLUBS, KIND_THREE),
      new Card(SUIT_CLUBS, KIND_TWO),
      new Card(SUIT_DIAMOND, KIND_ACE),
      new Card(SUIT_DIAMOND, KIND_KING),
      new Card(SUIT_DIAMOND, KIND_QUEEN),
      new Card(SUIT_DIAMOND, KIND_JACK),
      new Card(SUIT_DIAMOND, KIND_TEN),
      new Card(SUIT_DIAMOND, KIND_NINE),
      new Card(SUIT_DIAMOND, KIND_EIGHT),
      new Card(SUIT_DIAMOND, KIND_SEVEN),
      new Card(SUIT_DIAMOND, KIND_SIX),
      new Card(SUIT_DIAMOND, KIND_FIVE),
      new Card(SUIT_DIAMOND, KIND_FOUR),
      new Card(SUIT_DIAMOND, KIND_THREE),
      new Card(SUIT_DIAMOND, KIND_TWO),
      new Card(SUIT_HEART, KIND_ACE),
      new Card(SUIT_HEART, KIND_KING),
      new Card(SUIT_HEART, KIND_QUEEN),
      new Card(SUIT_HEART, KIND_JACK),
      new Card(SUIT_HEART, KIND_TEN),
      new Card(SUIT_HEART, KIND_NINE),
      new Card(SUIT_HEART, KIND_EIGHT),
      new Card(SUIT_HEART, KIND_SEVEN),
      new Card(SUIT_HEART, KIND_SIX),
      new Card(SUIT_HEART, KIND_FIVE),
      new Card(SUIT_HEART, KIND_FOUR),
      new Card(SUIT_HEART, KIND_THREE),
      new Card(SUIT_HEART, KIND_TWO),
      new Card(SUIT_SPADE, KIND_ACE),
      new Card(SUIT_SPADE, KIND_KING),
      new Card(SUIT_SPADE, KIND_QUEEN),
      new Card(SUIT_SPADE, KIND_JACK),
      new Card(SUIT_SPADE, KIND_TEN),
      new Card(SUIT_SPADE, KIND_NINE),
      new Card(SUIT_SPADE, KIND_EIGHT),
      new Card(SUIT_SPADE, KIND_SEVEN),
      new Card(SUIT_SPADE, KIND_SIX),
      new Card(SUIT_SPADE, KIND_FIVE),
      new Card(SUIT_SPADE, KIND_FOUR),
      new Card(SUIT_SPADE, KIND_THREE),
      new Card(SUIT_SPADE, KIND_TWO),
      new Card(SUIT_CLUBS, KIND_ACE),
      new Card(SUIT_CLUBS, KIND_KING),
      new Card(SUIT_CLUBS, KIND_QUEEN),
      new Card(SUIT_CLUBS, KIND_JACK),
      new Card(SUIT_CLUBS, KIND_TEN),
      new Card(SUIT_CLUBS, KIND_NINE),
      new Card(SUIT_CLUBS, KIND_EIGHT),
      new Card(SUIT_CLUBS, KIND_SEVEN),
      new Card(SUIT_CLUBS, KIND_SIX),
      new Card(SUIT_CLUBS, KIND_FIVE),
      new Card(SUIT_CLUBS, KIND_FOUR),
      new Card(SUIT_CLUBS, KIND_THREE),
      new Card(SUIT_CLUBS, KIND_TWO),
      new Card(SUIT_DIAMOND, KIND_ACE),
      new Card(SUIT_DIAMOND, KIND_KING),
      new Card(SUIT_DIAMOND, KIND_QUEEN),
      new Card(SUIT_DIAMOND, KIND_JACK),
      new Card(SUIT_DIAMOND, KIND_TEN),
      new Card(SUIT_DIAMOND, KIND_NINE),
      new Card(SUIT_DIAMOND, KIND_EIGHT),
      new Card(SUIT_DIAMOND, KIND_SEVEN),
      new Card(SUIT_DIAMOND, KIND_SIX),
      new Card(SUIT_DIAMOND, KIND_FIVE),
      new Card(SUIT_DIAMOND, KIND_FOUR),
      new Card(SUIT_DIAMOND, KIND_THREE),
      new Card(SUIT_DIAMOND, KIND_TWO),
      new Card(SUIT_HEART, KIND_ACE),
      new Card(SUIT_HEART, KIND_KING),
      new Card(SUIT_HEART, KIND_QUEEN),
      new Card(SUIT_HEART, KIND_JACK),
      new Card(SUIT_HEART, KIND_TEN),
      new Card(SUIT_HEART, KIND_NINE),
      new Card(SUIT_HEART, KIND_EIGHT),
      new Card(SUIT_HEART, KIND_SEVEN),
      new Card(SUIT_HEART, KIND_SIX),
      new Card(SUIT_HEART, KIND_FIVE),
      new Card(SUIT_HEART, KIND_FOUR),
      new Card(SUIT_HEART, KIND_THREE),
      new Card(SUIT_HEART, KIND_TWO),
      new Card(SUIT_SPADE, KIND_ACE),
      new Card(SUIT_SPADE, KIND_KING),
      new Card(SUIT_SPADE, KIND_QUEEN),
      new Card(SUIT_SPADE, KIND_JACK),
      new Card(SUIT_SPADE, KIND_TEN),
      new Card(SUIT_SPADE, KIND_NINE),
      new Card(SUIT_SPADE, KIND_EIGHT),
      new Card(SUIT_SPADE, KIND_SEVEN),
      new Card(SUIT_SPADE, KIND_SIX),
      new Card(SUIT_SPADE, KIND_FIVE),
      new Card(SUIT_SPADE, KIND_FOUR),
      new Card(SUIT_SPADE, KIND_THREE),
      new Card(SUIT_SPADE, KIND_TWO),
    ]

    // NOTE: knuth shuffle
    let ci = this.Deck.length, ri // current index, random index

    while (ci != 0) {
      ri = Math.floor(Math.random() * ci)
      ci--

      // NOTE: swap values using array destructuring
      [this.Deck[ci], this.Deck[ri]] = [this.Deck[ri], this.Deck[ci]]
    }
  }
}
